spring.application.name=capitalgains
#update this path as per your need for persisting h2 data for reuse
spring.datasource.url=jdbc:h2:file:F:/ws/demo-data/data
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
